import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from 'next/link';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vid-Box",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>

        <div className="container">
          {/* Temporary layout*/}
          <h1 id="start">Vid-Box</h1> {/*Placeholder Logo*/}
          <input type="text" id="search-bar" placeholder="Search"></input> {/*Non-fuctional search bar*/}
          <h1 id="end">profile pic</h1> {/*Placeholder Profile Pic*/}
        </div>
        <div className="row">
          <div className="nav-bar">
          <Link className="nav-bar-item" href="/">Home</Link>
          <Link className="nav-bar-item" href="/Profile">Profile</Link>
          <Link className="nav-bar-item" href="/Upload">Upload</Link>
          <Link className="nav-bar-item" href="/Login">Login</Link>
          </div>

          <div className="column">
            {children}
          </div>
        </div>
        
      </body>
    </html>
  );
}
